default: &default
  adapter: mysql2
  pool: 25
  username: root
  password: ''
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: checkers_development

test:
  <<: *default
  database: checkers_test